[package]
name = "mudband_ui"
version = "0.1.3"
description = "Your Band, Your World! Unite devices with a band!"
authors = ["Mudfish Networks <contact@mud.band>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "os-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
windows-named-pipe = "0.1.0"
windows = { version = "0.48", features = ["Win32_UI_Shell", "Win32_Foundation"] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
