name: Build on Android
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Build with Gradle
      run: (cd bin/mudband/android/Mudband && ./gradlew --no-daemon assembleDebug)
