name: Build mud.band for Linux
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build on ubuntu-latest
      run: (cd bin/mudband/linux && make clean && make)
